# Generated by Django 6.1 on 2026-08-10 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Промокод должен состоять из 8 заглавных латинских букв или из 8 цифр.', regex='^([A-Z]{8}|[0-9]{8})$')]),
        ),
    ]
