# Generated by Django 6.1 on 2026-08-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpromocode',
            name='promocode_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
