# Generated by Django 6.1 on 2026-08-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0002_alter_promocode_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCodeHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('promo_code', models.BigIntegerField(db_index=True)),
                ('is_success', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'promo_code_history',
            },
        ),
    ]
