# Generated by Django 6.1 on 2026-08-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0003_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Winner',
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_drawn',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='userpromocode',
            name='is_won',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpromocode',
            name='won_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='promocode',
            index=models.Index(condition=models.Q(('is_drawn', False)), fields=['id'], name='promocode_undrawn_id_idx'),
        ),
        migrations.AddIndex(
            model_name='userpromocode',
            index=models.Index(condition=models.Q(('won_on__isnull', False)), fields=['-won_on'], name='user_promocode_won_on_idx'),
        ),
        migrations.AddConstraint(
            model_name='userpromocode',
            constraint=models.UniqueConstraint(condition=models.Q(('is_won', True)), fields=('user_id',), name='unique_user_promocode_winner'),
        ),
    ]
