# Generated by Django 6.1 on 2026-08-11 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0003_promocodehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocodehistory',
            old_name='promo_code',
            new_name='promocode_id',
        ),
    ]
