# Generated by Django 6.1 on 2026-08-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0007_dailydraw_user_promocode_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydraw',
            name='promocode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_draws', to='promocode.promocode'),
        ),
    ]
