# Generated by Django 6.1 on 2026-08-12 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0008_alter_dailydraw_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailydraw',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_draws', to='promocode.promocode'),
        ),
    ]
