# Generated by Django 6.1 on 2026-08-12 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0009_alter_dailydraw_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
