# Generated by Django 6.1 on 2026-08-12 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0010_promocode_created_at_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpromocode',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
