# Generated by Django 6.1 on 2026-08-13 17:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0011_userpromocode_created_at_editable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPromocode',
            new_name='PromoActivation',
        ),
    ]
