# Generated by Django 6.1 on 2026-08-14 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0012_rename_userpromocode_promoactivation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='promocode',
            name='promocode_undrawn_taken_id_idx',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='is_drawn',
        ),
    ]
