# Generated by Django 6.1 on 2026-08-14 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0015_dailydraw_prize'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempted_code', models.CharField(db_index=True, max_length=8)),
                ('reason', models.CharField(choices=[('not_found', 'Не найден'), ('already_used', 'Уже использован')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='promo_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'promo_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'reason'], name='promo_attem_created_f6f05d_idx')],
            },
        ),
    ]
