# Generated by Django 6.1 on 2026-08-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promocode', '0016_promoattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailydraw',
            options={'ordering': ['-date', 'place'], 'verbose_name': 'Ежедневный розыгрыш', 'verbose_name_plural': 'Ежедневные розыгрыши'},
        ),
        migrations.AlterModelOptions(
            name='promoactivation',
            options={'verbose_name': 'Активация промокода', 'verbose_name_plural': 'Активации промокодов'},
        ),
        migrations.AlterModelOptions(
            name='promoattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Неудачная попытка', 'verbose_name_plural': 'Неудачные попытки'},
        ),
        migrations.AlterModelOptions(
            name='promocode',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
    ]
