# Generated by Django 6.1 on 2026-08-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_user_email_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notify_on_promocode',
            field=models.BooleanField(default=True),
        ),
    ]
