# Generated by Django 6.1 on 2026-08-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_user_notify_on_promocode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
