# Generated by Django 6.1 on 2026-08-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_user_birth_date_telephone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
